version: "3"
services:
  client:
    build: .
    image: loyaltytiers-client
    container_name: loyaltytiers-client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    # env_file:
    #   - ./.env