version: "3"
services:
  client:
    build:
     context: ./client
     dockerfile: Dockerfile
    image: loyaltytiers-client
    container_name: loyaltytiers-client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - ./client/.env
    depends_on:
      - server
  server:
    image: loyaltytiers-server
    container_name: loyaltytiers-server
    restart: always
    build:
     context: ./server
     dockerfile: Dockerfile
    ports:
      - ${API_PORT}:8080
    volumes:
      - ./server:/app # enable hot-reloading using nodemon to speed up development
      - /app/node_modules
    env_file:
      - ./server/.env
    depends_on:
      - db
  db:
    image: postgres
    container_name: loyaltytiers-postgres
    restart: always
    environment:
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./server/dataset:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - ./server/.env