version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  app:
    image: loyaltytiers-server
    ports:
      - 8080:3000


