version: '3'
services:
  db:
    image: postgres
    container_name: loyaltytiers-postgres
    restart: always
    environment:
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_PORT}:5432
  server:
    image: loyaltytiers-server
    container_name: loyaltytiers-server
    restart: always
    build:
      context: . # point at the Dockerfile in the current dir to auto build
    ports:
      - ${API_PORT}:8080
    volumes:
      - ./:/app # enable hot-reloading using nodemon to speed up development
      - /app/node_modules
